---
name: Slapr Slack emoji PR updates
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]

jobs:
  run_slapr:
    runs-on: ubuntu-latest
    env:
      SLAPR_MULTICHANNEL_TEAM_MAPPING: "slapr_team_mapping.json"
      GITHUB_TOKEN: "${{ secrets.SLAPR_GITHUB_TOKEN }}"
    steps:
      - name: Fetch team mapping file
        run: |
          echo '{"agent-devx-infra": "C06QEJ59XQF", "agent-devx-loops": "C07SHSHS3E3"}' > "$SLAPR_MULTICHANNEL_TEAM_MAPPING"
          echo 'Channels are #celian-tests and #yet-another-celian-tests'
      - uses: DataDog/slapr@celian/codeowners
        env:
          SLAPR_MULTICHANNEL: "true"
          SLAPR_MULTICHANNEL_ORG: "DataDog"
          SLACK_API_TOKEN: "${{ secrets.SLACK_API_TOKEN }}"
          SLAPR_BOT_USER_ID: "${{ secrets.SLAPR_BOT_USER_ID }}"
          SLAPR_EMOJI_REVIEW_STARTED: "review_started"
          SLAPR_EMOJI_APPROVED: "pr-approved-"
          SLAPR_EMOJI_CHANGES_REQUESTED: "changes_requested"
          SLAPR_EMOJI_MERGED: "merged"
          SLAPR_EMOJI_CLOSED: "closed"
